board/urls.py
from django.conf.urls.static import static
from django.conf import settings

from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('profile/', include("profiles.urls")),
    path("accounts/", include("allauth.urls")),
    # path('accounts/', include('django.contrib.auth.urls')),
    # path("accounts/", include("accounts.urls")),
    path('', include("config.urls")),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

config/models.py
from django.urls import reverse

from django.contrib.auth.models import User
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey
from django.core.cache import cache


class Category(MPTTModel):
    name = models.CharField('Имя', max_length=50, unique=True)
    """категории объявлений"""
    parent = TreeForeignKey(
        'self',
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name='children',
        verbose_name="Родитель"
    )
    slug = models.SlugField('url', max_length=50, unique=True)

    def __str__(self):
        return self.name

    class MPTTMeta:
        order_insertion_by = ['name']
        verbose_name = "Категория"




class FilterAdvert(models.Model):
    """"Фильтры"""
    name = models.CharField('Имя', max_length=50, unique=True)
    slug = models.SlugField('url', max_length=50, unique=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Фильтр'
        verbose_name_plural = 'Фильтры'
        ordering = ["id"]


class DateAdvert(models.Model):
    """"Срок для объявления"""
    name = models.CharField('Имя', max_length=50, unique=True)
    slug = models.SlugField('url', max_length=50)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Срок'
        verbose_name_plural = 'Сроки'
        ordering = ["id"]



class Advert(models.Model):
    """Объявления"""
    user = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.CASCADE)
    category = models.ForeignKey(Category, verbose_name='Категория', on_delete=models.CASCADE)
    filters = models.ForeignKey(FilterAdvert, verbose_name='Фильтр', on_delete=models.CASCADE)
    date = models.ForeignKey(DateAdvert, verbose_name='Срок', on_delete=models.CASCADE)
    subject = models.CharField('Тема', max_length=200)
    description = models.TextField("Объявление", max_length=10000)
    images = models.ForeignKey('gallery.Gallery', verbose_name='Изображения', blank=True, null=True, on_delete=models.SET_NULL)
    file = models.FileField("Файл", upload_to='board/', blank=True, null=True)
    price = models.DecimalField('Цена', max_digits=20, decimal_places=2)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    moderation = models.BooleanField('Модерация', default=False)
    # TODO: для slug генерить путь (user, subject)
    slug = models.SlugField('url', max_length=200, unique=True)
    rating = models.SmallIntegerField("Лайки", default=0)


    def __str__(self):
        return self.subject



    """Добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с объявлениями"""
    #def get_absolute_url(self):
        #return f'/advert/{self.id}'

    #def save(self, *args, **kwargs):
      #  super().save(*args, **kwargs)  # сначала вызываем метод родителя, чтобы объект сохранился
       # cache.delete(f'advert-{self.id}')  # затем удаляем его из кэша, чтобы сбросить его

    # def get_absolute_url(self):
    #     return reverse("advert-detail", kwargs={"category": self.category.slug, "slug": self.slug})

    def get_absolute_url(self):
       return reverse('advert-detail', kwargs={'pk': self.pk})

    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()

    def preview(self):
        return self.description[0:124] + '...'


    class Meta:
        verbose_name = 'Объявление'
        verbose_name_plural = 'Объявления'


class Comment(models.Model):
    commentAdvert = models.ForeignKey(Advert, on_delete=models.CASCADE)
    commentUser = models.ForeignKey(User, on_delete=models.CASCADE)
    description = models.TextField("Объявление", max_length=10000)
    created = models.DateTimeField('Дата создания', auto_now_add=True)
    rating = models.SmallIntegerField("Комментарий", default=0)


    def like(self):
        self.rating += 1
        self.save()

    def dislike(self):
        self.rating -= 1
        self.save()


class Reviews(models.Model):
    """Отзывы"""
    email = models.EmailField()
    user = models.CharField("Пользователь", max_length=100)
    text = models.TextField("Отзыв", max_length=5000)
    parent = models.ForeignKey(
        'self', verbose_name="Родитель", on_delete=models.SET_NULL, blank=True, null=True
    )
    advert = models.ForeignKey(Advert, verbose_name="Объявление", on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user} - {self.advert}"

    class Meta:
        verbose_name = "Отзыв"
        verbose_name_plural = 'Отзывы'



class Subscription(models.Model):
    user = models.ForeignKey(
        to=User,
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )
    category = models.ForeignKey(
        to='Category',
        on_delete=models.CASCADE,
        related_name='subscriptions',
    )

board/templates/board/advert-detail.html
{% extends 'default.html' %}
{% load custom_filters %}

{% block title %}
Advert
{% endblock title %}
{% block content %}

        <h2>Тема: {{ advert.subject }}</h2>
        <p>Объявление: {{ advert.description }}</p>
        <p>

            {% if advert.file %}
            <p>Изображения: <img src="{{ advert.file.url }}" style="width: 200px;" alt=""></p>
        {% endif %}


<!--            1{% for photo in advert.images.photos.all %}-->
<!--            1{% if photo.image %}-->
<!--            1<p>Изображения: <img src="{{ photo.image.url }}" style="width: 200px;" alt=""></p>-->
<!--       1 {% endif %}-->

<!--            % for photo in advert.images.photos.all %}-->

<!--                {% if photo.image %}-->
<!--                    <img src="{{ photo.image.url }}" style="width: 200px;">-->
<!--                {% endif %}-->
<!--            {% endfor %}-->


        </p>
        <p>Срок: {{ advert.date }}</p>
        <p>Рубрика:{{ advert.filters }}</p>
        <p>Пользователь: {{ advert.user }}</p>
        <p>Цена: {{ advert.price|currency }}</p>
        <p>Дата создания: {{ advert.created }}</p>
        <hr>


<br><br>

                    <div class="row">
                        <div class="single-form-left">
                            <!-- contact form grid -->
                            <div class="contact-single">
                                <h3 class="editContent" style="outline: none; cursor: inherit;">
                                    <span class="sub-tittle editContent"
                                          style="outline: none; cursor: inherit;"></span>Оставить отзыв</h3>
                                <form action="{% url 'add_review' advert.id %}" method="post" class="mt-4">
                                    {%  csrf_token %}
                                    <div class="form-group editContent"
                                         style="outline: none; cursor: inherit;">
                                        <label for="contactcomment" class="editContent"
                                               style="outline: none; cursor: inherit;">Ваш комментарий
                                            *</label>
                                        <textarea class="form-control border" rows="5" name="text"
                                                  id="contactcomment" required=""></textarea>
                                    </div>
                                    <div class="d-sm-flex">
                                        <div class="col-sm-6 form-group p-0 editContent"
                                             style="outline: none; cursor: inherit;">
                                            <label for="contactusername" class="editContent"
                                                   style="outline: none; cursor: inherit;">Имя
                                                *</label>
                                            <input type="text" class="form-control border" name="user"
                                                   id="contactusername" required="">
                                        </div>
                                        <div class="col-sm-6 form-group ml-sm-3 editContent"
                                             style="outline: none; cursor: inherit;">
                                            <label for="contactemail" class="editContent"
                                                   style="outline: none; cursor: inherit;">Email
                                                *</label>
                                            <input type="email" class="form-control border" name="email"
                                                   id="contactemail" required="">
                                        </div>
                                    </div>
                                    <button type="submit"
                                            class="mt-3 btn btn-success btn-block py-3"
                                            style="outline: none; cursor: inherit;">Отправить
                                    </button>
                                </form>
                            </div>
                            <!--  //contact form grid ends here -->
                            </div>
                            {% for review in advert.reviews_set.all %}
                               <div class="media body mt-4">
                                   <h5 class="mt-0 editContent">
                                       {{ review.user }}
                                   </h5>
                                   <p class="mt-2 editContent">
                                       {{ review.text }}
                                   </p>
                               </div>
                            {% endfor %}

<br><br><br><br>
<div><hr></div>
<br><br>
<div>
    {% if perms.config.change_advert %}
    <a href= "{% url 'advert_update' advert.id %}"><button>Редактировать</button></a>
    {% endif %}
    {% if perms.config.delete_advert %}
    <a href= "{% url 'advert_delete' advert.id %}"><button>Удалить</button></a>
    {% endif %}
</div>

<br><br><br>

{% endblock content %}

board/templates/board/advert-list.html
{% extends 'default.html' %}

{% load custom_filters %}

{% load custom_tags %}


{% block title %}
Adverts
{% endblock title %}

{% block content %}

          <h2>Объявления</h2>
    <hr>
    <br>
        {# Добавляем форму, которая объединяет набор полей, которые будут отправляться в запросе #}
           <form action="" method="get">
        <!--       {# Переменная, которую мы передали через контекст, может сгенерировать нам форму с полями #}-->
               {{ filterset.form.as_p }}
        <!--       {# Добавим кнопку отправки данных формы #}-->
               <input type="submit" value="Найти" />
           </form>


        <br><br>
          <hr>

    {% for advert in object_list %}

        <h2><a href="{{ advert.get_absolute_url }}">{{ advert.subject|truncatechars:45 }}</a></h2>
        <p>Рубрика: {{ advert.filters }}</p>
        <p>Цена: {{ advert.price|currency }}</p>
        <p>Дата создания: {{ advert.created }}</p>
        <p>Пользователь: {{ advert.user }}</p>

<!--        {% if advert.images %}-->
<!--            <p>Изображение: <img scr="{{ advert.images.url }}" style="width: 200px;" alt=""></p>-->
<!--        {% endif %}-->

<!--{% for photo in advert.images.photos.all %}-->

<!--        1{% if photo.image %}-->
<!--            1<p>Изображения: <img src="{{ photo.image.url }}" style="width: 90px;" alt=""></p>-->
<!--        1{% endif %}-->

        <p>
            {% if advert.file %}
            <p>Изображения: <img src="{{ advert.file.url }}" style="width: 60px;" alt=""></p>
            {% endif %}

        </p>

<!--                {% if photo.image %}-->
<!--                    <img src="{{ photo.image.url }}" style="width: 80px;">-->
<!--                {% endif %}-->
<!--            {% endfor %}-->
        <hr>


    {% endfor %}


<!--{# Добавляем пагинацию на страницу #}-->

<!--   {# Информация о предыдущих страницах #}-->
   {% if page_obj.has_previous %}
       <a href="?{% url_replace page=1 %}">1</a>
       {% if page_obj.previous_page_number != 1 %}
           ...
           <a href="?{% url_replace page=page_obj.previous_page_number %}">{{ page_obj.previous_page_number }}</a>
       {% endif %}
   {% endif %}

<!--   {# Информация о текущей странице #}-->
   {{ page_obj.number }}

<!--   {# Информация о следующих страницах #}-->
   {% if page_obj.has_next %}
       <a href="?{% url_replace page=page_obj.next_page_number %}">{{ page_obj.next_page_number }}</a>
       {% if paginator.num_pages != page_obj.next_page_number %}
           ...
           <a href="?{% url_replace page=page_obj.paginator.num_pages %}">{{ page_obj.paginator.num_pages }}</a>
       {% endif %}
   {% endif %}

    <br>
    <br>

<!--<a href="http://127.0.0.1:8000/posts/create"><button>Создать</button></a> &nbsp;&nbsp;&nbsp;-->
{% if perms.config.add_advert %}
<a href="http://127.0.0.1:8000/create/"><button>Создать</button></a>
{% endif %}
&nbsp;&nbsp;&nbsp;
    <br>
    <br>

{% endblock content %}

board/templates/board/advert_delete.html
{% extends 'default.html' %}

{% block content %}
<h1>Удаление объявления {{ object.subject }}</h1>
<br>
<hr>
<br><br>
{% if user == advert_user %}
<form action="" method="post">
    {% csrf_token %}
    <p>Удаляем "{{ object.subject }}"? </p>
    <input type="submit" value="Да!" />
</form>
{% else %}
<h3>Вы не можете удалить это объявление!</h3>
{% endif %}
{% endblock content %}

board/templates/board/advert_edit.html
{% extends 'default.html' %}

{% block content %}
<h1>Изменить объявление {{ object.subject }}</h1>
<hr>
{% if user == advert_user %}
<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Сохранить" />
</form>
{% else %}
<h3>Вы не можете редактировать это объявление!</h3>
{% endif %}
{% endblock content %}